Repository COS301-SE-2022/Conversation-Catcher, pull requests merged in 2022-09, with the labels that each got.

#327 Update local store
  apps/client/package.json
  apps/client/src/app/App.tsx
  apps/client/src/app/slices/pdf.slice.ts
  apps/client/src/app/slices/user.slice.ts
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-tile/__snapshots__/pdf-tile.spec.js.snap
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.spec.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  package.json
  yarn.lock
Labels: priority:high, scope:ui, status:not-ready, type:feature, type:fix

#335 🎉 Testing api layer
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.spec.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/repository/data-access/src/lib/mongodb-access.spec.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.spec.ts
  libs/api/summarise-text/api/src/lib/api-summarise-text-api.resolver.spec.ts
  libs/api/summarise-text/service/src/lib/api-summarise-text-service.service.spec.ts
Labels: priority:medium, scope:cicd, status:ready, type:test

#346 Persist login
  apps/client/src/app/slices/pdf.slice.ts
  apps/client/src/app/slices/user.slice.ts
  libs/client/ui/src/lib/change-email/change-email.js
  libs/client/ui/src/lib/change-password/change-password.js
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/settings/settings.js
Labels: priority:high, scope:ui, status:ready, type:fix

#365 ✨: Connect speech to text to create pdfs from speech
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/repository/data-access/src/lib/mongodb-access.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.spec.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/set-pdf-manager.command.ts
  libs/api/speech-to-text/deepspeech/.gitignore
  libs/api/speech-to-text/deepspeech/speech-to-text-server.py
  libs/api/speech-to-text/deepspeech/speechToText.py
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.ts
  libs/api/user-management/repository/data-access/src/lib/mongodb-access.ts
  libs/api/user-management/service/src/lib/commands/handlers/add-user.handler.ts
  libs/api/user-management/service/src/lib/commands/handlers/groups.handler.ts
  libs/client/ui/src/lib/change-email/change-email.js
  libs/client/ui/src/lib/change-password/change-password.js
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
Labels: priority:high, scope:ui, scope:service, type:feature, type:fix

#366 ♻️: Use Azure speech to text
  libs/api/speech-to-text/deepspeech/speech-to-text-server.py
Labels: priority:high, scope:service, status:ready, type:refactor

#371 🐛: Fix issues on the backend and warnings on the ui
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/repository/data-access/src/lib/mongodb-access.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.spec.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/delete-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/set-pdf-manager.command.ts
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.ts
  libs/api/user-management/service/src/lib/commands/handlers/add-user.handler.ts
  libs/api/user-management/service/src/lib/queries/handlers/groups.handler.ts
  libs/api/user-management/service/src/lib/user-management-service.module.ts
  libs/api/user-management/service/src/lib/user-management-service.service.ts
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, scope:service

#372 Pdf gen
  apps/client/package.json
  apps/client/src/app/App.tsx
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/register/register.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/shared-components/document/document.js
  libs/client/ui/src/lib/shared-components/document/document.spec.js
  libs/client/ui/src/lib/shared-components/loading/loading.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  package.json
  yarn.lock
Labels: priority:high, scope:ui, type:feature, type:fix

#378 ✨: Add summarisation for text in documents
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.spec.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/repository/data-access/src/lib/mongodb-access.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/set-pdf-manager.command.ts
  libs/api/summarise-text/api/src/lib/api-summarise-text-api.resolver.ts
  libs/api/summarise-text/huggingface/summarise-text-server.py
  libs/api/summarise-text/service/src/lib/api-summarise-text-service.module.ts
  libs/api/summarise-text/service/src/lib/api-summarise-text-service.service.spec.ts
  libs/api/summarise-text/service/src/lib/commands/handlers/summarise-summarise-text.handlers.ts
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
Labels: priority:high, scope:ui, scope:service, type:feature

#379 Pdf generation
  apps/client/ios/Podfile
  apps/client/package.json
  apps/client/src/app/App.tsx
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/shared-components/document/document.js
  libs/client/ui/src/lib/shared-components/document/document.spec.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.spec.js
  package.json
  patches/react-native-html-to-pdf+0.12.0.patch
  yarn.lock
Labels: priority:high, scope:ui, type:feature

#385 Group integration
  apps/client/src/app/slices/group.slice.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service.service.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/handlers/get-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/impl/get-pdf-manager.query.ts
  libs/api/user-management/api/data-access/src/lib/group.entity.ts
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.ts
  libs/api/user-management/service/src/lib/commands/handlers/groups.handler.ts
  libs/api/user-management/service/src/lib/commands/impl/groups.command.ts
  libs/api/user-management/service/src/lib/queries/handlers/groups.handler.ts
  libs/api/user-management/service/src/lib/user-management-service.module.ts
  libs/api/user-management/service/src/lib/user-management-service.service.ts
  libs/client/ui/src/lib/group-info/group-info.js
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/shared-components/group-display/group-display.js
  libs/client/ui/src/lib/shared-components/group-tile/group-tile.js
  libs/client/ui/src/lib/shared-components/loading/loading.js
  libs/client/ui/src/lib/shared-components/local-groups-access/local-groups-access.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, status:ready, type:change, type:feature, type:fix, type:refactor

#386 Splash screen
  apps/client/src/app/App.tsx
  libs/client/ui/src/lib/assets/LOGO.jpg
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/shared-components/splash/splash.js
  libs/client/ui/src/lib/shared-components/splash/splash.spec.js
Labels: priority:high, scope:ui, status:ready, type:feature, type:fix

#387 Name generation and ios
  libs/api/generate-names/AI/.gitignore
  libs/api/generate-names/AI/__pycache__/attention.cpython-310.pyc
  libs/api/generate-names/AI/generateTextFiles.py
  libs/api/generate-names/AI/nameGenerator copy.py
  libs/api/generate-names/AI/nameGenerator.py
  libs/api/generate-names/AI/requirements.txt
  libs/api/generate-names/AI/reverse_source_word_index
  libs/api/generate-names/AI/reverse_target_word_index
  libs/api/generate-names/AI/source_word_index
  libs/api/generate-names/AI/target_word_index
  libs/api/generate-names/AI/tensorflow_cloud_training.py
  libs/api/generate-names/AI/train_name_generation.py
Labels: priority:high, scope:service, type:feature

#390 Name generation and i os
  libs/api/generate-names/AI/train_name_generation.py
Labels: priority:high, scope:service, type:fix
