Repository COS301-SE-2022/Conversation-Catcher, pull requests merged in 2022-06, with the labels that each got.

#106 ➕: Add dependencies for graphql environment
  apps/api/src/app/app.module.ts
  libs/api/database-manager/api/feature/src/lib/api-database-manager-api-feature.module.ts
  libs/api/database-manager/api/feature/src/lib/database-manager.resolver.spec.ts
  libs/api/database-manager/api/feature/src/lib/database-manager.resolver.ts
  libs/api/shell/src/lib/api-shell.module.ts
  package.json
  tsconfig.base.json
  workspace.json
  yarn.lock
Labels: priority:high, scope:api, status:ready, type:feature

#116 ➕ : Add @nestjs/cqrs for service layer
  package.json
  yarn.lock
Labels: priority:high, scope:service, status:ready

#122 Test snapshots to see what is breaking
  libs/client/ui/src/lib/home/home.spec.js
Labels: priority:low, scope:cicd, status:ready, type:fix

#123 Test snapshot fix
  libs/client/ui/src/lib/login/login.spec.js
  libs/client/ui/src/lib/settings/settings.spec.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.spec.js
  libs/client/ui/src/lib/view-all/view-all.spec.js
Labels: priority:low, scope:cicd, status:ready, type:fix

#128 Ui changes
  apps/client/android/app/build.gradle
  apps/client/package.json
  libs/client/ui/jest.config.ts
  libs/client/ui/src/lib/home/__snapshots__/home.spec.js.snap
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/login/__snapshots__/login.spec.js.snap
  libs/client/ui/src/lib/settings/__snapshots__/settings.spec.js.snap
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/shared-components/pdf-tile/__snapshots__/pdf-tile.spec.js.snap
  libs/client/ui/src/lib/view-all/__snapshots__/view-all.spec.js.snap
  libs/client/ui/src/lib/view-all/view-all.js
  libs/client/ui/src/lib/view-all/view-all.spec.js
  package.json
  yarn.lock
Labels: priority:high, scope:ui, type:cosmetic

#132 ✨: Add calls to connect mongodb and services
  libs/api/database-manager/api/feature/src/lib/database-manager.resolver.ts
  libs/api/database-manager/service/feature/src/lib/database-manager.service.ts
Labels: priority:medium, scope:db, status:ready, type:feature

#133 ✨ add service layer for pdf manager
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service-feature.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service-feature.service.spec.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service-feature.service.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/events/delete-pdf-manager.event.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/events/delete-pdf-manager.event.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/events/index.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/events/set-pdf-manager.event.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/events/set-pdf-manager.event.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/delete-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/index.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/delete-pdf-manager.command.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/index.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/impl/set-pdf-manager.command.ts
  libs/api/pdf-manager/service/feature/src/lib/models/index.ts
  libs/api/pdf-manager/service/feature/src/lib/models/pdf-manager-service-feature.model.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/handlers/get-pdf-manager.handlers.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/handlers/index.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/impl/get-pdf-manager.query.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/impl/index.ts
  libs/api/pdf/api/data-access/.babelrc
  libs/api/pdf/api/data-access/.eslintrc.json
  libs/api/pdf/api/data-access/README.md
  libs/api/pdf/api/data-access/jest.config.ts
  libs/api/pdf/api/data-access/project.json
  libs/api/pdf/api/data-access/src/index.ts
  libs/api/pdf/api/data-access/src/lib/api-pdf-api-data-access.module.ts
  libs/api/pdf/api/data-access/src/lib/pdf.entity.spec.ts
  libs/api/pdf/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf/api/data-access/tsconfig.json
  libs/api/pdf/api/data-access/tsconfig.lib.json
  libs/api/pdf/api/data-access/tsconfig.spec.json
  libs/api/pdf/api/feature/.babelrc
  libs/api/pdf/api/feature/.eslintrc.json
  libs/api/pdf/api/feature/README.md
  libs/api/pdf/api/feature/jest.config.ts
  libs/api/pdf/api/feature/project.json
  libs/api/pdf/api/feature/src/index.ts
  libs/api/pdf/api/feature/src/lib/api-pdf-api-feature.module.ts
  libs/api/pdf/api/feature/src/lib/api-pdf-api-feature.resolver.spec.ts
  libs/api/pdf/api/feature/src/lib/api-pdf-api-feature.resolver.ts
  libs/api/pdf/api/feature/tsconfig.json
  libs/api/pdf/api/feature/tsconfig.lib.json
  libs/api/pdf/api/feature/tsconfig.spec.json
  libs/api/pdf/service/feature/.babelrc
  libs/api/pdf/service/feature/.eslintrc.json
  libs/api/pdf/service/feature/README.md
  libs/api/pdf/service/feature/jest.config.ts
  libs/api/pdf/service/feature/project.json
  libs/api/pdf/service/feature/src/index.ts
  libs/api/pdf/service/feature/src/lib/api-pdf-service-feature.module.ts
  libs/api/pdf/service/feature/src/lib/api-pdf-service-feature.service.spec.ts
  libs/api/pdf/service/feature/src/lib/api-pdf-service-feature.service.ts
  libs/api/pdf/service/feature/tsconfig.json
  libs/api/pdf/service/feature/tsconfig.lib.json
  libs/api/pdf/service/feature/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: priority:high, scope:service, status:on-hold, type:feature

#135 :sparkles: adding to pdf manager api
  libs/api/pdf-manager/api/data-access/src/index.ts
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.spec.ts
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.module.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.spec.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/service/feature/src/index.ts
Labels: priority:medium, scope:api, status:ready, type:feature

#136 ➕ Added dependencies for redux
  package.json
  yarn.lock
Labels: priority:high, scope:ui, status:ready, type:feature

#140 🚑: Fix error for api to run
  package.json
  yarn.lock
Labels: priority:high, scope:api, status:ready, type:fix

#137 🎨 changes to pdf manager api
  libs/api/pdf-manager/api/data-access/src/lib/pdf.entity.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
Labels: priority:medium, scope:api, status:on-hold, type:change

#146 UI additions
  apps/client/android/app/build.gradle
  apps/client/android/app/src/main/AndroidManifest.xml
  apps/client/android/app/src/main/java/com/client/MainApplication.java
  apps/client/android/build.gradle
  apps/client/package.json
  apps/client/src/app/App.tsx
  libs/client/ui/jest.config.ts
  libs/client/ui/src/lib/assets/Bug introduction a modification of code.pdf
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/home/__snapshots__/home.spec.js.snap
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/settings/__snapshots__/settings.spec.js.snap
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/shared-components/pdf-tile/__snapshots__/pdf-tile.spec.js.snap
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/view-all/__snapshots__/view-all.spec.js.snap
  libs/client/ui/src/lib/view-all/view-all.js
  package.json
  tsconfig.base.json
  yarn.lock
Labels: priority:high

#152 ✨: Add getAllPdfs for a user
  libs/api/database-manager/api/feature/src/lib/database-manager.resolver.ts
  libs/api/database-manager/service/feature/src/lib/database-manager.service.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/handlers/get-pdf-manager.handlers.ts
Labels: priority:high, scope:db, status:needs-tests, type:feature

#164 Update api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
Labels: priority:high, scope:api, status:ready, type:change

#165 🐛 : Let update commands return updated object
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
Labels: priority:high, scope:db, scope:service, type:fix

#167 🐛: Small changes to finetune service-api interaction
  libs/api/database-manager/api/feature/src/lib/database-manager.resolver.ts
  libs/api/database-manager/service/feature/src/lib/database-manager.service.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.module.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service-feature.module.ts
  libs/api/pdf-manager/service/feature/src/lib/api-pdf-manager-service-feature.service.ts
  libs/api/shell/src/lib/api-shell.module.ts
Labels: priority:high, scope:api, scope:service, type:fix

#166 Audio Recording
  apps/client/android/app/src/main/AndroidManifest.xml
  apps/client/package.json
  libs/client/ui/jest.config.ts
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/view-all/__snapshots__/view-all.spec.js.snap
  libs/client/ui/src/lib/view-all/view-all.js
  package.json
  yarn.lock
Labels: priority:high, scope:ui
