Repository COS301-SE-2022/Conversation-Catcher, pull requests merged in 2022-10, with the labels that each got.

#396 UI updates
  .gitignore
  apps/api/src/app/app.module.ts
  apps/client/src/app/slices/user.slice.ts
  libs/api/generate-names/AI/Dockerfile
  libs/api/generate-names/service/src/lib/api-generate-names-service.service.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
  libs/api/pdf-manager/service/feature/src/lib/queries/handlers/get-pdf-manager.handler.ts
  libs/api/pdf-manager/shared/src/lib/global.vars.ts
  libs/api/speech-to-text/deepspeech/speech-to-text-server.py
  libs/api/summarise-text/service/src/lib/commands/handlers/summarise-summarise-text.handlers.ts
  libs/api/user-management/api/data-access/src/lib/user.entity.ts
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.spec.ts
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.ts
  libs/api/user-management/repository/data-access/src/lib/mongodb-access.ts
  libs/api/user-management/service/src/lib/commands/handlers/add-user.handler.ts
  libs/api/user-management/service/src/lib/commands/impl/add-user.command.ts
  libs/api/user-management/service/src/lib/user-management-service.service.ts
  libs/client/ui/src/lib/change-email/change-email.js
  libs/client/ui/src/lib/change-password/change-password.js
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/forgot-password/forgot-password.js
  libs/client/ui/src/lib/group-info/group-info.js
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/register/register.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/shared-components/group-tile/group-tile.js
  libs/client/ui/src/lib/shared-components/member-tile/member-tile.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, type:fix, type:refactor

#397 Group fixes
  apps/client/src/app/App.tsx
  apps/client/src/app/slices/group.slice.spec.ts
  apps/client/src/app/slices/group.slice.ts
  libs/api/user-management/service/src/lib/commands/handlers/groups.handler.ts
  libs/client/ui/src/lib/group-info/group-info.js
  libs/client/ui/src/lib/group-selection/group-selection.js
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/shared-components/group-display/group-display.js
  libs/client/ui/src/lib/shared-components/group-tile/group-tile.js
  libs/client/ui/src/lib/shared-components/member-tile/member-tile.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, scope:api, status:ready, type:fix, type:refactor

#401 UI updates
  apps/client/android/app/src/main/res/drawable/ic_launcher_background.xml
  apps/client/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  apps/client/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  apps/client/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  apps/client/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  apps/client/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  apps/client/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  apps/client/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  apps/client/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  apps/client/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  apps/client/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  apps/client/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  apps/client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  apps/client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  apps/client/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  apps/client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  apps/client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  apps/client/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  apps/client/android/app/src/main/res/playstore-icon.png
  apps/client/android/app/src/main/res/values/strings.xml
  libs/api/generate-names/service/src/lib/api-generate-names-service.service.ts
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/client/ui/src/index.ts
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/group-info/group-info.js
  libs/client/ui/src/lib/group-selection/group-selection.js
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/shared-components/group-display/group-display.js
  libs/client/ui/src/lib/shared-components/loading/loading.js
  libs/client/ui/src/lib/shared-components/loading/loading.spec.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, type:cosmetic

#402 Final bug fixes
  libs/client/ui/src/lib/group-info/group-info.js
  libs/client/ui/src/lib/groups/groups.js
  libs/client/ui/src/lib/shared-components/group-display/group-display.js
  libs/client/ui/src/lib/shared-components/group-tile/group-tile.js
  libs/client/ui/src/lib/shared-components/local-groups-access/local-groups-access.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.js
  libs/client/ui/src/lib/shared-components/member-tile/member-tile.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, status:ready, type:feature, type:fix, type:refactor
