Repository COS301-SE-2022/Conversation-Catcher, pull requests merged in 2022-05, with the labels that each got.

#20 🐛 ✨: Added codecov and fixed bugs
  .github/workflows/main.yml
Labels: priority:high

#19 ➕: added graphql
  package.json
  yarn.lock
Labels: priority:high, scope:repository

#31 ✨: add entity folder for api
  libs/api/database-manager/api/interface/.babelrc
  libs/api/database-manager/api/interface/.eslintrc.json
  libs/api/database-manager/api/interface/README.md
  libs/api/database-manager/api/interface/jest.config.ts
  libs/api/database-manager/api/interface/project.json
  libs/api/database-manager/api/interface/src/index.ts
  libs/api/database-manager/api/interface/src/lib/api-database-manager-api-interface.module.ts
  libs/api/database-manager/api/interface/tsconfig.json
  libs/api/database-manager/api/interface/tsconfig.lib.json
  libs/api/database-manager/api/interface/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: priority:high, scope:api, status:ready, type:feature

#34 Initial ViewAll files
  libs/client/ui/src/lib/view-all/view-all.spec.tsx
  libs/client/ui/src/lib/view-all/view-all.tsx
  tsconfig.base.json
  workspace.json
Labels: priority:high, scope:ui, type:feature

#36 ➕: add nestjs/graphql
  package.json
  yarn.lock
Labels: priority:high, status:ready, type:feature

#35 ✨ Adding pdf library
  libs/api/pdf-manager/api/.babelrc
  libs/api/pdf-manager/api/.eslintrc.json
  libs/api/pdf-manager/api/README.md
  libs/api/pdf-manager/api/jest.config.ts
  libs/api/pdf-manager/api/project.json
  libs/api/pdf-manager/api/src/index.ts
  libs/api/pdf-manager/api/src/lib/api-pdf-manager-api.module.ts
  libs/api/pdf-manager/api/src/lib/pdf-manager-api.resolver.spec.ts
  libs/api/pdf-manager/api/src/lib/pdf-manager-api.resolver.ts
  libs/api/pdf-manager/api/tsconfig.json
  libs/api/pdf-manager/api/tsconfig.lib.json
  libs/api/pdf-manager/api/tsconfig.spec.json
  libs/api/pdf-manager/service/.babelrc
  libs/api/pdf-manager/service/.eslintrc.json
  libs/api/pdf-manager/service/README.md
  libs/api/pdf-manager/service/jest.config.ts
  libs/api/pdf-manager/service/project.json
  libs/api/pdf-manager/service/src/index.ts
  libs/api/pdf-manager/service/src/lib/api-pdf-manager-service.module.ts
  libs/api/pdf-manager/service/src/lib/pdf-manager-service.spec.ts
  libs/api/pdf-manager/service/src/lib/pdf-manager-service.ts
  libs/api/pdf-manager/service/tsconfig.json
  libs/api/pdf-manager/service/tsconfig.lib.json
  libs/api/pdf-manager/service/tsconfig.spec.json
  tsconfig.base.json
  workspace.json
Labels: priority:high, scope:api, scope:service, type:feature

#37 Created files and added styles to home.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/home/home.spec.js
Labels: priority:high, scope:ui, type:feature

#41 Update home.js
  libs/client/ui/src/lib/home/home.js
Labels: priority:high, scope:ui

#39 Added the required styles for the View All PDFs page
  libs/client/ui/src/lib/view-all/view-all.js
  libs/client/ui/src/lib/view-all/view-all.spec.js
  libs/client/ui/src/lib/view-all/view-all.tsx
Labels: priority:high, scope:ui, status:ready, type:feature, type:cosmetic

#42 Added styles home.js
  libs/client/ui/src/lib/home/home.js
Labels: scope:ui

#43 Added styles to home.js
  libs/client/ui/src/lib/home/home.js
Labels: priority:high, scope:ui

#46 Added the remaining ui components to the View All PDFs page
  libs/client/ui/src/lib/assets/23a067db3896c1ac956e0e22fe9c7588.png
  libs/client/ui/src/lib/assets/2b2d102eac55f56c11649d75b48bf464.png
  libs/client/ui/src/lib/assets/4517a97e95ebe8ad3751a63a5759b6d2.png
  libs/client/ui/src/lib/assets/634a9d41d1a919acda75dccb24941e81.png
  libs/client/ui/src/lib/assets/6784b72f243ed3938b4effbf0ffc0c7a.png
  libs/client/ui/src/lib/assets/822a4ffacfed7a8c6c870fe46d9baffd.png
  libs/client/ui/src/lib/assets/bedbbc4af4182ff9461b234dfb880971.png
  libs/client/ui/src/lib/assets/cc91d6ae1ee6693ad1312f5f6a5ca71d.png
  libs/client/ui/src/lib/assets/cf60ecb68aa83021ee8ce615fa41038e.png
  libs/client/ui/src/lib/assets/eb280550057d075f24cdd330438abed1.png
  libs/client/ui/src/lib/assets/f762e82c40c63fd888499d8d139bcf08.png
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, status:ready, type:feature, type:cosmetic

#50 Created Common Component Library
  libs/client/shared-components/.babelrc
  libs/client/shared-components/.eslintrc.json
  libs/client/shared-components/README.md
  libs/client/shared-components/jest.config.js
  libs/client/shared-components/project.json
  libs/client/shared-components/src/index.js
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.js
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.spec.js
  libs/client/shared-components/test-setup.js
  libs/client/shared-components/tsconfig.json
  libs/client/shared-components/tsconfig.lib.json
  libs/client/shared-components/tsconfig.spec.json
  libs/client/ui/src/lib/home/home.js
Labels: priority:high, scope:ui

#51 Imported component and updated settings
  apps/client/src/app/App.spec.tsx
  apps/client/src/app/App.tsx
  apps/client/tsconfig.app.json
  apps/client/tsconfig.spec.json
  tsconfig.base.json
Labels: priority:high, scope:ui

#53 Routing
  apps/client/src/app/App.tsx
  apps/client/tsconfig.json
  libs/client/ui/src/index.ts
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/view-all/view-all.js
  package.json
  yarn.lock
Labels: priority:high, scope:ui, status:ready, type:feature

#60 Settings changes
  apps/client/src/app/App.tsx
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.spec.js
  workspace.json
Labels: priority:high, scope:ui

#67 Added develop branch to actions
  .github/workflows/main.yml
Labels: priority:high, scope:cicd, status:ready, type:fix

#66 ✨(ui): Add settings
  apps/client/package.json
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/assets/754d89ce51e0854b878e2ef557f04bde.png
  libs/client/ui/src/lib/assets/79679bee68e57c649afa27a8de7f3414.png
  libs/client/ui/src/lib/assets/c2a1ee46204a89d839eacd0921c2b2f7.png
  libs/client/ui/src/lib/assets/de8bda761eb9ceb32e01cf462e01ee7b.png
  libs/client/ui/src/lib/assets/f762e82c40c63fd888499d8d139bcf08 copy.png
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/settings/settings.spec.js
Labels: priority:high, scope:ui, status:needs-tests, type:feature

#68 UI fix
  apps/client/android/build.gradle
  apps/client/android/gradlew
  apps/client/android/gradlew.bat
  apps/client/package.json
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui

#71 Update package.json
  apps/client/package.json
Labels: priority:high, scope:ui

#72 ✨ Routing for settings
  apps/client/src/app/App.tsx
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/settings/settings.js
Labels: priority:medium, scope:ui, status:ready, type:feature

#73 Fixed UI Structure
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/settings/settings.js
Labels: priority:high, scope:ui

#74 Merge develop into main
  .github/workflows/main.yml
  apps/client/android/build.gradle
  apps/client/android/gradlew
  apps/client/android/gradlew.bat
  apps/client/package.json
  apps/client/src/app/App.tsx
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.js
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.spec.js
  libs/client/ui/src/lib/assets/754d89ce51e0854b878e2ef557f04bde.png
  libs/client/ui/src/lib/assets/79679bee68e57c649afa27a8de7f3414.png
  libs/client/ui/src/lib/assets/c2a1ee46204a89d839eacd0921c2b2f7.png
  libs/client/ui/src/lib/assets/de8bda761eb9ceb32e01cf462e01ee7b.png
  libs/client/ui/src/lib/assets/f762e82c40c63fd888499d8d139bcf08 copy.png
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/settings/settings.spec.js
  libs/client/ui/src/lib/view-all/view-all.js
  workspace.json
Labels: priority:high, scope:ui, scope:repository, status:ready, type:fix

#75 Update readme on develop
  README.md
Labels: priority:low, scope:repository, status:ready, type:cosmetic, type:documentation

#77 ➕:Added react-test-renderer
  libs/client/shared-components/src/lib/pdf-tile/__snapshots__/pdf-tile.spec.js.snap
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.js
  libs/client/shared-components/src/lib/pdf-tile/pdf-tile.spec.js
  libs/client/ui/src/lib/home/__snapshots__/home.spec.js.snap
  libs/client/ui/src/lib/home/home.spec.js
  libs/client/ui/src/lib/settings/__snapshots__/settings.spec.js.snap
  libs/client/ui/src/lib/settings/settings.spec.js
  libs/client/ui/src/lib/view-all/__snapshots__/view-all.spec.js.snap
  libs/client/ui/src/lib/view-all/view-all.spec.js
  package.json
  yarn.lock
Labels: priority:high, scope:repository, type:test
