Repository COS301-SE-2022/Conversation-Catcher, pull requests merged in 2022-08, with the labels that each got.

#248 ✨: Add firebase authentication for android
  .vscode/settings.json
  apps/client/android/app/build.gradle
  apps/client/android/app/google-services.json
  apps/client/android/build.gradle
  apps/client/package.json
  apps/client/src/app/App.tsx
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/register/register.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/test-setup.ts
Labels: priority:high, scope:ui, status:ready, type:feature

#268 Local user setup complete with firebase integration for authentication
  apps/client/src/app/App.tsx
  apps/client/src/app/slices/colour.slice.spec.ts
  apps/client/src/app/slices/colour.slice.ts
  apps/client/src/app/slices/email.slice.spec.ts
  apps/client/src/app/slices/email.slice.ts
  apps/client/src/app/slices/pdf.slice.spec.ts
  apps/client/src/app/slices/pdf.slice.ts
  apps/client/src/app/slices/user.slice.spec.ts
  apps/client/src/app/slices/user.slice.ts
  libs/api/user-management/api/feature/src/lib/user-management-api-feature.resolver.ts
  libs/api/user-management/repository/data-access/src/lib/mongodb-access.ts
  libs/api/user-management/service/src/lib/commands/handlers/add-user.handler.ts
  libs/api/user-management/service/src/lib/commands/impl/add-user.command.ts
  libs/api/user-management/service/src/lib/commands/impl/index.ts
  libs/api/user-management/service/src/lib/user-management-service.module.ts
  libs/api/user-management/service/src/lib/user-management-service.service.ts
  libs/client/ui/src/lib/change-email/change-email.js
  libs/client/ui/src/lib/change-email/change-email.spec.js
  libs/client/ui/src/lib/change-password/change-password.js
  libs/client/ui/src/lib/change-password/change-password.spec.js
  libs/client/ui/src/lib/colour-page/colour-page.js
  libs/client/ui/src/lib/colour-page/colour-page.spec.js
  libs/client/ui/src/lib/forgot-password/forgot-password.js
  libs/client/ui/src/lib/forgot-password/forgot-password.spec.js
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/login/login.spec.js
  libs/client/ui/src/lib/register/register.js
  libs/client/ui/src/lib/register/register.spec.js
  libs/client/ui/src/lib/settings/settings.js
  libs/client/ui/src/lib/settings/settings.spec.js
  libs/client/ui/src/lib/shared-components/pdf-tile/__snapshots__/pdf-tile.spec.js.snap
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.spec.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.spec.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:high, scope:ui, scope:api, status:not-ready, type:change, type:feature, type:fix

#306 ✨: Add error handling of input
  libs/client/ui/src/lib/change-email/change-email.js
  libs/client/ui/src/lib/change-password/change-password.js
  libs/client/ui/src/lib/forgot-password/forgot-password.js
  libs/client/ui/src/lib/login/login.js
  libs/client/ui/src/lib/register/register.js
Labels: priority:medium, scope:ui, status:ready, type:feature

#311 🐛 ♻️: Refactor pdf display and fix pdf delete and rename
  libs/client/ui/src/index.ts
  libs/client/ui/src/lib/home/home.js
  libs/client/ui/src/lib/register/register.spec.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.js
  libs/client/ui/src/lib/shared-components/local-pdfs-access/local-pdfs-access.spec.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.js
  libs/client/ui/src/lib/shared-components/pdf-display/pdf-display.spec.js
  libs/client/ui/src/lib/shared-components/pdf-tile/pdf-tile.js
  libs/client/ui/src/lib/shared-components/pdf-view/pdf-view.js
  libs/client/ui/src/lib/view-all/view-all.js
Labels: priority:medium, scope:ui, status:needs-tests, type:fix

#312 ♻️:Change pdfs to use assignedid and not given id
  libs/api/pdf-manager/api/feature/src/lib/api-pdf-manager-api-feature.resolver.ts
  libs/api/pdf-manager/repository/data-access/src/lib/mongodb-access.ts
  libs/api/pdf-manager/service/feature/src/lib/commands/handlers/set-pdf-manager.handler.ts
Labels: priority:low, scope:api, status:ready, type:refactor
